CREATE TABLE `twusers` (
  `id` bigint(20) unsigned NOT NULL,
  `screen_name` varchar(15) NOT NULL,
  `name` varchar(20) DEFAULT NULL,
  `description` text,
  `followers_count` int(11) unsigned DEFAULT NULL,
  `friends_count` int(11) unsigned DEFAULT NULL,
  `url` varchar(322) DEFAULT NULL,
  `lang` varchar(10) DEFAULT NULL,
  `location` varchar(30) DEFAULT NULL,
  `time_zone` varchar(50) DEFAULT NULL,
  `utc_offset` int(10) DEFAULT NULL,
  `profile_image_url` varchar(322) DEFAULT NULL,
  `profile_image_url_https` varchar(322) DEFAULT NULL,
  `protected` tinyint(1) unsigned DEFAULT NULL,
  `verified` tinyint(1) unsigned DEFAULT NULL,
  `accesskey` varchar(256) DEFAULT NULL,
  `accesssecret` varchar(256) DEFAULT NULL,
  `status` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `screen_name` (`screen_name`),
  KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;